[package]
name = "carreltex-engine"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
carreltex-core = { path = "../carreltex-core" }
carreltex-xdv = { path = "../carreltex-xdv" }
